site_name: Manual de Implantação

nav:
  - Página Inicial: index.md
  - Requisitos:
    - Introdução: modulos/requisitos/introducao.md
  - Componentes:
    - Introdução: modulos/componentes/introducao.md
    - Backend: modulos/componentes/backend.md
#    - Instalação: componentes/instalacao.md
#    - Configuração: componentes/configuracao.md
#    - Testes: componentes/testes.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.search.highlight
    - navigation.search.suggest
    - navigation.search.share
    - navigation.search.suggest
    - navigation.search.share
    - navigation.search.highlight
    - navigation.search.suggest
    - navigation.search.share
