site_name: Manual de Implantação

nav:
  - Página Inicial: index.md
  - Componentes:
    - Introdução: modulos/componentes/introducao.md
    - Componentes Principais: modulos/componentes/principais.md
    - Componentes Acessórios: modulos/componentes/acessorios.md
  - Infraestrutura Recomendada:
    - Infraestrutura de referência: modulos/recursoMinimo/infraestrutura.md
  - Arquitetura:
    - Arquitetura do Sistema: modulos/arquitetura/arquitetura.md
  - Preparação do Ambiente:
    - Preparação do Ambiente: modulos/ambiente/ambiente.md
  - Instalação da aplicação:
    - Instalação com Docker Compose: modulos/instalacao/compose.md
    - Instalação com Kubernetes: modulos/instalacao/kubernetes.md
    - Load Balance e Redundância: modulos/instalacao/loadbalance.md
    - Banco de Dados: modulos/instalacao/bancodedados.md
    - Banco de Dados Chave-valor: modulos/instalacao/cache.md
    - Check-list pós instalação: modulos/instalacao/checklist.md
  - Boas Práticas:
    - Boas Práticas: modulos/praticas/boaspraticas.md
  - Resolvendo Problemas:
    - Troubleshooting: modulos/problemas/problemas.md
  - Referências:
    - Referências: modulos/referencias/referencia.md

theme:
  name: readthedocs
  logo: assets/icons/favicon100.png
  formats:
    - epub
    - pdf

plugins:
  - search
  - mermaid2
